command_timeout = 10000

right_format = "$python$golang$nodejs"

format = """
[┌───────────────────](fg:bright-black)$time$cmd_duration$status
[│](fg:bright-black)$os$hostname [/](fg:bright-black) $username
[└──⎡](fg:bright-black) $directory$git_branch$git_status [⎦](fg:bright-black) $character
"""
[fill]
symbol = "─"
style = "cyan"

[username]
format = '[$user]($style)'
style_user = 'fg:green'
style_root = 'fg:red'
disabled = false
show_always = true

[os]
format = "[$symbol]($style)"
style = "fg:green bold"
disabled = false

[os.symbols]
Macos = " "
Kali = "  "
Ubuntu = " "
Windows = " "

[hostname]
format = '[$hostname]($style)'
style = "fg:green"
ssh_only = false

[cmd_duration]
format = '[───⎡](fg:bright-black)[ 祥 $duration ]($style)[⎦](fg:bright-black)'
style = 'fg:bright-black'

[directory]
format = '[ $path]($style)'
style = 'fg:cyan'

[git_branch]
format = '[ ❮$symbol $branch]($style)'
symbol = ''
style = 'fg:green'
truncation_length = 30

[git_status]
format = '[ $all_status]($style)[❯](fg:green)'
style = 'fg:bright-red '

[status]
format = '[───⎡](fg:bright-black)[ $symbol$status ]($style)[⎦](fg:bright-black)'
symbol = ''
style = 'fg:bright-red'
disabled = false

[character]
success_symbol = '[](fg:bright-black)'
error_symbol = '[](fg:bright-black)'

[time]
format = '[⎡](fg:bright-black)[ $time ]($style)[⎦](fg:bright-black)'
style = 'fg:cyan'
disabled = false

[custom.tun]
command = 'ifconfig tun0 | grep -oP "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}" | head -1'
shell = ["/bin/bash"]
when = "ifconfig tun0"
format = "[⎡](fg:bright-black)[  $output ](fg:blue)[⎦](fg:bright-black)"

# Languages

[python]
format = '[⎡](fg:bright-black)[ $symbol ($virtualenv )$version ]($style)[⎦](fg:bright-black)'
symbol = ''
style = 'fg:yellow'

[golang]
format = '[⎡](fg:bright-black)[ $symbol $version ]($style)[⎦](fg:bright-black)'
symbol = ''
style = 'fg:blue'

[nodejs]
format = '[⎡](fg:bright-black)[ $symbol $version ]($style)[⎦](fg:bright-black)'
symbol = ''
style = 'fg:green'