command_timeout = 10000

right_format = "$python$golang$nodejs"

format = """
$fill$status[ ](cyan)$time$cmd_duration
[ ](fg:yellow bg:cyan)$username$hostname[ ](cyan)${custom.tun}
[▍](cyan)$directory$git_branch$git_status $character
"""
[fill]
symbol = "▁"
style = "cyan"

[username]
format = '[ $user]($style)'
style_user = 'fg:bright-purple bg:cyan'
style_root = 'fg:bright-red'
disabled = false
show_always = true

[hostname]
format = '[$hostname]($style)'
style = "fg:yellow bg:cyan"
ssh_only = false

[cmd_duration]
format = '[ 祥 $duration ]($style)'
style = 'fg:bright-black bg:cyan'

[directory]
format = '[ $path]($style)'
style = 'fg:cyan'

[git_branch]
format = '[$symbol $branch]($style)'
symbol = ''
style = 'fg:green '
truncation_length = 30

[git_status]
format = '[ $all_status]($style)[](green)'
style = 'fg:bright-red '

[status]
format = '[ ](bright-red)[$symbol$status]($style)[](bright-red)'
symbol = ''
style = 'fg:black bg:bright-red'
disabled = false

[character]
success_symbol = '[](fg:cyan)'
error_symbol = '[](fg:cyan)'

[time]
format = '[ $time ]($style)'
style = 'fg:purple bg:cyan'
disabled = false

[custom.tun]
command = 'ifconfig tun0 | grep -oP "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}" | head -1'
shell = ["/bin/bash"]
when = "ifconfig tun0"
format = "[ ](yellow)[ $output](fg:black bg:yellow)[ ](yellow)"

# Languages

[python]
format = '[$symbol ($virtualenv )$version]($style)'
symbol = ''
style = 'fg:yellow'

[golang]
format = '[$symbol $version]($style)'
symbol = ''
style = 'fg:blue'

[nodejs]
format = '[$symbol $version]($style)'
symbol = ''
style = 'fg:green'
