right_format = "$python$golang$nodejs"

format = """
$fill $status$time$cmd_duration
[┌─](bright-black)$username$hostname${custom.tun}
[└──](bright-black)$directory$git_branch$git_status
  $character
"""
[fill]
symbol = " "

[username]
format = '[\[ ](bright-black)[$user]($style)'
style_user = 'fg:blue'
style_root = 'fg:bright-red'
disabled = false
show_always = true

[hostname]
format = '[ at](bright-black)[ $hostname]($style)[ \]](bright-black)'
style = "fg:blue"
ssh_only = false

[cmd_duration]
format = '[─\[](bright-black)[ 祥 $duration]($style)[\]](bright-black)'
style = 'fg:bright-blue'

[directory]
format = '[\[ ](bright-black)[ $path]($style)[ \]](bright-black)'
style = 'fg:cyan'

[git_branch]
format = '[─\[ ](bright-black)[$symbol $branch]($style)'
symbol = ''
style = 'fg:green'
truncation_length = 30

[git_status]
format = '[ $all_status]($style)[ \]](bright-black)'
style = 'fg:bright-red'

[status]
format = '[\[ ](bright-black)[$symbol$status]($style)[ \]─](bright-black)'
symbol = ''
style = 'fg:bright-red'
disabled = false

[character]
success_symbol = '[](fg:bright-black)'
error_symbol = '[](fg:bright-black)'

[time]
format = '[\[ ](bright-black)[$time]($style)[ \]](bright-black)'
style = 'fg:purple'
disabled = false

[custom.tun]
command = 'ifconfig tun0 | grep -oP "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}" | head -1'
#command = "echo test"
shell = ["/bin/bash"]
when = "true"
format = "[─\\[](bright-black) [ $output](cyan) [\\]](bright-black)"

# Languages

[python]
format = '[\[ ](bright-black)[$symbol ($virtualenv )$version]($style)[ \]](bright-black)'
symbol = ''
style = 'fg:yellow'

[golang]
format = '[\[ ](bright-black)[$symbol $version]($style)[ \]](bright-black)'
symbol = ''
style = 'fg:blue'

[nodejs]
format = '[\[ ](bright-black)[$symbol $version]($style)[ \]](bright-black)'
symbol = ''
style = 'fg:green'