command_timeout = 10000

format = """
[](fg:bright-black bg:#07283d bold)[$os$hostname$username$directory$git_branch$git_status$python$golang$nodejs$cmd_duration$status](bg:bright-black)[](fg:bright-black bg:#07283d bold)$fill$tun
  
  $character
"""
[fill]
symbol = " "
style = "cyan"

[os]
format = "[$symbol]($style)"
style = "fg:bright-white bg:bright-black bold"
disabled = false

[os.symbols]
Macos = " "
Kali = "  "
Ubuntu = " "
Windows = " "

[username]
format = '[  $user ]($style)'
style_user = 'fg:bright-white bg:bright-black bold'
style_root = 'fg:red bg:bright-black bold' 
disabled = false
show_always = true

[hostname]
format = '[$hostname]($style)'
style = "fg:bright-white bg:bright-black bold"
ssh_only = false

[cmd_duration]
format = '[󰔛 $duration]($style)'
style = 'fg:bright-white bg:bright-black italic'

[directory]
format = '[  $path ]($style)'
style = 'fg:bright-white bg:bright-black italic bold'

[git_branch]
format = '[ $symbol $branch ]($style)'
symbol = '󰊢'
style = 'fg:bright-cyan bg:bright-black'
truncation_length = 30

[git_status]
format = '[ $all_status ]($style)'
style = 'fg:bright-red bg:bright-black'

[status]
format = '[$symbol$status]($style)'
symbol = ''
style = 'fg:bright-red bg:bright-black'
disabled = false

[character]
success_symbol = '[](fg:bright-black bold)'
error_symbol = '[](fg:bright-black bold)'

[time]
format = '[⎡](fg:bright-black)[ $time ]($style)[⎦](fg:bright-black)'
style = 'fg:cyan'
disabled = false

[custom.tun]
command = 'ifconfig tun0 | grep -oP "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}" | head -1'
shell = ["/bin/bash"]
when = "ifconfig tun0"
format = "[](fg:bright-black bg:#07283d bold)[ $output](bg:bright-black)[](fg:bright-black bg:#07283d bold)"

# Languages

[python]
format = '[ $symbol ($virtualenv )$version ]($style)'
symbol = ''
style = 'fg:yellow bg:bright-black'

[golang]
format = '[ $symbol $version ]($style)'
symbol = ''
style = 'fg:blue bg:bright-black'

[nodejs]
format = '[$symbol $version ]($style)'
symbol = ''
style = 'fg:green bg:bright-black'
