command_timeout = 10000

format = """
┏━⎡ $username $os$hostname$custom $directory⎦$fill$git_branch$git_status
┃$fill$python$golang$nodejs$cmd_duration
┗━━ $status$character
"""

right_format = ""

[fill]
symbol = " "
style = "cyan"

[os]
format = "[$symbol]($style)"
style = "fg:bright-cyan bold"
disabled = false

[os.symbols]
Macos = " "
Kali = "  "
Ubuntu = " "
Windows = " "

[username]
format = '[ ]($style)[$user](fg:bright-white)'
style_user = 'fg:bright-cyan bold'
style_root = 'fg:bright-red  bold' 
disabled = false
show_always = true

[hostname]
format = '[$hostname]($style)'
style = "fg:bright-white"
ssh_only = false

[cmd_duration]
format = '[ 󰔛 $duration ]($style)'
style = 'fg:bright-white bg:bright-black'

[directory]
format = '[](fg:bright-cyan bold)[ $path ]($style)'
style = 'fg:white italic'

[git_branch]
format = '[ $symbol $branch]($style)'
symbol = '󰊢'
style = 'fg:bright-cyan bg:bright-black'
truncation_length = 30

[git_status]
format = '[ $all_status ]($style)'
style = 'fg:red bg:bright-black'

[status]
format = '[$symbol $status]($style) '
symbol = '󱐌'
style = 'fg:red'
disabled = false

[character]
success_symbol = '[ :](fg:cyan bold)'
error_symbol = '[ :](fg:cyan bold)'

[time]
format = '[⎡](fg:bright-black)[ $time ]($style)[⎦](fg:bright-black)'
style = 'fg:cyan'
disabled = false

[custom.tun]
command = 'ifconfig tun0 | grep -oP "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}" | head -1'
shell = ["/bin/bash"]
when = "ifconfig tun0"
format = " [  $output ](fg:bright-yellow bg:bright-black) "

# Languages

[python]
format = ' [ $symbol ($virtualenv )$version ]($style)'
symbol = ''
style = 'fg:yellow bg:bright-black'

[golang]
format = ' [ $symbol $version ]($style)'
symbol = ''
style = 'fg:blue bg:bright-black'

[nodejs]
format = ' [ $symbol $version ](fg:green bg:bright-black)'
symbol = ''
