include-file = ~/.config/polybar/modules.ini
include-file = ~/.config/polybar/colors.ini

[bar/elite]
monitor = Virtual1
bottom = true
override-redirect = true

; Size and padding
height = 25
padding = 1
line-size = 1
width = 90%
offset-x = 5%
offset-y = 1%
module-margin = 0
border-size = 1
border-color = ${colors.yellow}

; Colors
background = ${colors.background}
foreground = ${colors.foreground}

; Fonts
font-0 = "Hack Nerd Font:pixelsize=10:weight=bold;2"
font-1 = "Hack Nerd Font:pixelsize=12:weight=bold;2"
font-2 = "Hack Nerd Font:pixelsize=14:weight=bold;2"

; Modules
modules-left = menu i3
modules-right = filesystem cpu memory network1 network2 time date
