if &background == 'dark'
  let s:guishade0 = "#042024"
  let s:guishade1 = "#0F3539"
  let s:guishade2 = "#1A4B4E"
  let s:guishade3 = "#256063"
  let s:guishade4 = "#317578"
  let s:guishade5 = "#3C8A8D"
  let s:guishade6 = "#47A0A2"
  let s:guishade7 = "#52B5B7"
  let s:guiaccent0 = "#CD6966"
  let s:guiaccent1 = "#5FF7E2"
  let s:guiaccent2 = "#29D6BF"
  let s:guiaccent3 = "#69DDCE"
  let s:guiaccent4 = "#30F3D9"
  let s:guiaccent5 = "#38CCC9"
  let s:guiaccent6 = "#3DFFE5"
  let s:guiaccent7 = "#2AC6C3"
  let s:shade0 = 23
  let s:shade1 = 23
  let s:shade2 = 60
  let s:shade3 = 66
  let s:shade4 = 66
  let s:shade5 = 73
  let s:shade6 = 73
  let s:shade7 = 116
  let s:accent0 = 174
  let s:accent1 = 122
  let s:accent2 = 80
  let s:accent3 = 116
  let s:accent4 = 86
  let s:accent5 = 80
  let s:accent6 = 86
  let s:accent7 = 80
endif

let s:p = {'normal': {}, 'inactive': {}, 'insert': {}, 'replace': {}, 'visual': {}, 'tabline': {}}
let s:p.normal.left = [ [ s:guishade1, s:guiaccent5, s:shade1, s:accent5 ], [ s:guishade7, s:guishade2, s:shade7, s:shade2 ] ]
let s:p.normal.right = [ [ s:guishade1, s:guishade4, s:shade1, s:shade4 ], [ s:guishade5, s:guishade2, s:shade5, s:shade2 ] ]
let s:p.inactive.right = [ [ s:guishade1, s:guishade3, s:shade1, s:shade3 ], [ s:guishade3, s:guishade1, s:shade3, s:shade1 ] ]
let s:p.inactive.left =  [ [ s:guishade4, s:guishade1, s:shade4, s:shade1 ], [ s:guishade3, s:guishade0, s:shade3, s:shade0 ] ]
let s:p.insert.left = [ [ s:guishade1, s:guiaccent3, s:shade1, s:accent3 ], [ s:guishade7, s:guishade2, s:shade7, s:shade2 ] ]
let s:p.replace.left = [ [ s:guishade1, s:guiaccent1, s:shade1, s:accent1 ], [ s:guishade7, s:guishade2, s:shade7, s:shade2 ] ]
let s:p.visual.left = [ [ s:guishade1, s:guiaccent6, s:shade1, s:accent6 ], [ s:guishade7, s:guishade2, s:shade7, s:shade2 ] ]
let s:p.normal.middle = [ [ s:guishade5, s:guishade1, s:shade5, s:shade1 ] ]
let s:p.inactive.middle = [ [ s:guishade4, s:guishade1, s:shade4, s:shade1 ] ]
let s:p.tabline.left = [ [ s:guishade6, s:guishade2, s:shade6, s:shade2 ] ]
let s:p.tabline.tabsel = [ [ s:guishade6, s:guishade0, s:shade6, s:shade0 ] ]
let s:p.tabline.middle = [ [ s:guishade2, s:guishade4, s:shade2, s:shade4 ] ]
let s:p.tabline.right = copy(s:p.normal.right)
let s:p.normal.error = [ [ s:guiaccent0, s:guishade0, s:accent0, s:shade0 ] ]
let s:p.normal.warning = [ [ s:guiaccent2, s:guishade1, s:accent2, s:shade1 ] ]

let g:lightline#colorscheme#ThemerMyColorSet#palette = s:p